project:
  type: website
  output-dir: docs

website:
  site-url: "https://ayelbatac.github.io"
  page-navigation: true

  navbar:
    title: "<a href='/' style='display: flex; align-items: center; gap: 0.5rem; text-decoration: none; color: white;'>
          <img src='logo.png' alt='Logo' style='height: 60px;'>
          <span style='font-weight: 500; letter-spacing: 0.08em;'>AYEL L. R. BATAC</span>
        </a>"
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Knowledge Translation"
        menu:
          - text: "Infographics"
            href: infographics.qmd
          - text: "Blog"
            href: blog.qmd
          - text: "Talks and Presentations"
            href: talks.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    css: styles.css
    anchor-links: false
    favicon: favicon.ico

    include-in-header:
      - meta.html
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap" rel="stylesheet">

    include-after-body: footer.html